/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHubIndexRouteImport } from './routes/_authenticated/hub/index'
import { Route as AuthenticatedOnboardingWelcomeRouteImport } from './routes/_authenticated/onboarding/welcome'
import { Route as AuthenticatedOnboardingTutorialRouteImport } from './routes/_authenticated/onboarding/tutorial'
import { Route as AuthenticatedOnboardingProfileSetupRouteImport } from './routes/_authenticated/onboarding/profile-setup'
import { Route as AuthenticatedAdventureNewRouteImport } from './routes/_authenticated/adventure/new'
import { Route as AuthenticatedAdventureIdRouteImport } from './routes/_authenticated/adventure/$id'
import { Route as AuthenticatedAdventureIdSummaryRouteImport } from './routes/_authenticated/adventure/$id.summary'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHubIndexRoute = AuthenticatedHubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingWelcomeRoute =
  AuthenticatedOnboardingWelcomeRouteImport.update({
    id: '/onboarding/welcome',
    path: '/onboarding/welcome',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingTutorialRoute =
  AuthenticatedOnboardingTutorialRouteImport.update({
    id: '/onboarding/tutorial',
    path: '/onboarding/tutorial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingProfileSetupRoute =
  AuthenticatedOnboardingProfileSetupRouteImport.update({
    id: '/onboarding/profile-setup',
    path: '/onboarding/profile-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdventureNewRoute =
  AuthenticatedAdventureNewRouteImport.update({
    id: '/adventure/new',
    path: '/adventure/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdventureIdRoute =
  AuthenticatedAdventureIdRouteImport.update({
    id: '/adventure/$id',
    path: '/adventure/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdventureIdSummaryRoute =
  AuthenticatedAdventureIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedAdventureIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/adventure/$id': typeof AuthenticatedAdventureIdRouteWithChildren
  '/adventure/new': typeof AuthenticatedAdventureNewRoute
  '/onboarding/profile-setup': typeof AuthenticatedOnboardingProfileSetupRoute
  '/onboarding/tutorial': typeof AuthenticatedOnboardingTutorialRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/hub/': typeof AuthenticatedHubIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/adventure/$id/summary': typeof AuthenticatedAdventureIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/adventure/$id': typeof AuthenticatedAdventureIdRouteWithChildren
  '/adventure/new': typeof AuthenticatedAdventureNewRoute
  '/onboarding/profile-setup': typeof AuthenticatedOnboardingProfileSetupRoute
  '/onboarding/tutorial': typeof AuthenticatedOnboardingTutorialRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/hub': typeof AuthenticatedHubIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/adventure/$id/summary': typeof AuthenticatedAdventureIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/adventure/$id': typeof AuthenticatedAdventureIdRouteWithChildren
  '/_authenticated/adventure/new': typeof AuthenticatedAdventureNewRoute
  '/_authenticated/onboarding/profile-setup': typeof AuthenticatedOnboardingProfileSetupRoute
  '/_authenticated/onboarding/tutorial': typeof AuthenticatedOnboardingTutorialRoute
  '/_authenticated/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/_authenticated/hub/': typeof AuthenticatedHubIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/adventure/$id/summary': typeof AuthenticatedAdventureIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/adventure/$id'
    | '/adventure/new'
    | '/onboarding/profile-setup'
    | '/onboarding/tutorial'
    | '/onboarding/welcome'
    | '/hub/'
    | '/settings/'
    | '/adventure/$id/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/adventure/$id'
    | '/adventure/new'
    | '/onboarding/profile-setup'
    | '/onboarding/tutorial'
    | '/onboarding/welcome'
    | '/hub'
    | '/settings'
    | '/adventure/$id/summary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/_authenticated/adventure/$id'
    | '/_authenticated/adventure/new'
    | '/_authenticated/onboarding/profile-setup'
    | '/_authenticated/onboarding/tutorial'
    | '/_authenticated/onboarding/welcome'
    | '/_authenticated/hub/'
    | '/_authenticated/settings/'
    | '/_authenticated/adventure/$id/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/': {
      id: '/_authenticated/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof AuthenticatedHubIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/welcome': {
      id: '/_authenticated/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthenticatedOnboardingWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/tutorial': {
      id: '/_authenticated/onboarding/tutorial'
      path: '/onboarding/tutorial'
      fullPath: '/onboarding/tutorial'
      preLoaderRoute: typeof AuthenticatedOnboardingTutorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/profile-setup': {
      id: '/_authenticated/onboarding/profile-setup'
      path: '/onboarding/profile-setup'
      fullPath: '/onboarding/profile-setup'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adventure/new': {
      id: '/_authenticated/adventure/new'
      path: '/adventure/new'
      fullPath: '/adventure/new'
      preLoaderRoute: typeof AuthenticatedAdventureNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adventure/$id': {
      id: '/_authenticated/adventure/$id'
      path: '/adventure/$id'
      fullPath: '/adventure/$id'
      preLoaderRoute: typeof AuthenticatedAdventureIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adventure/$id/summary': {
      id: '/_authenticated/adventure/$id/summary'
      path: '/summary'
      fullPath: '/adventure/$id/summary'
      preLoaderRoute: typeof AuthenticatedAdventureIdSummaryRouteImport
      parentRoute: typeof AuthenticatedAdventureIdRoute
    }
  }
}

interface AuthenticatedAdventureIdRouteChildren {
  AuthenticatedAdventureIdSummaryRoute: typeof AuthenticatedAdventureIdSummaryRoute
}

const AuthenticatedAdventureIdRouteChildren: AuthenticatedAdventureIdRouteChildren =
  {
    AuthenticatedAdventureIdSummaryRoute: AuthenticatedAdventureIdSummaryRoute,
  }

const AuthenticatedAdventureIdRouteWithChildren =
  AuthenticatedAdventureIdRoute._addFileChildren(
    AuthenticatedAdventureIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdventureIdRoute: typeof AuthenticatedAdventureIdRouteWithChildren
  AuthenticatedAdventureNewRoute: typeof AuthenticatedAdventureNewRoute
  AuthenticatedOnboardingProfileSetupRoute: typeof AuthenticatedOnboardingProfileSetupRoute
  AuthenticatedOnboardingTutorialRoute: typeof AuthenticatedOnboardingTutorialRoute
  AuthenticatedOnboardingWelcomeRoute: typeof AuthenticatedOnboardingWelcomeRoute
  AuthenticatedHubIndexRoute: typeof AuthenticatedHubIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdventureIdRoute: AuthenticatedAdventureIdRouteWithChildren,
  AuthenticatedAdventureNewRoute: AuthenticatedAdventureNewRoute,
  AuthenticatedOnboardingProfileSetupRoute:
    AuthenticatedOnboardingProfileSetupRoute,
  AuthenticatedOnboardingTutorialRoute: AuthenticatedOnboardingTutorialRoute,
  AuthenticatedOnboardingWelcomeRoute: AuthenticatedOnboardingWelcomeRoute,
  AuthenticatedHubIndexRoute: AuthenticatedHubIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
